# Generated by Django 5.2.5 on 2025-10-01 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
